default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: racoon_server_development
  #username: racoon_server
  #password:
  #host: localhost
  port: 5433

test:
  <<: *default
  database: racoon_server_test

production:
  <<: *default
  database: racoon_server_production
  username: racoon_server
  password: <%= ENV['RACOON_SERVER_DATABASE_PASSWORD'] %>
  #     url: <%= ENV['DATABASE_URL'] %>
