default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: racoon_server_development
  #username: final_project_server
  #password:
  #host: localhost
  #port: 5432

test:
  <<: *default
  database: racoon_server_test

production:
  <<: *default
  database: final_project_server_production
  username: final_project_server
  password: <%= ENV['FINAL_PROJECT_SERVER_DATABASE_PASSWORD'] %>
  #     url: <%= ENV['DATABASE_URL'] %>
